site_name: Track Builder
site_description: Documentation for the Track Builder Plugin
site_author: TheEpicTwin
repo_name: Twin1Twin2/track-builder
repo_url: https://github.com/Twin1Twin2/track-builder

nav:
  - Home: index.md
  - Changelog: changelog.md
  - Quick Start:
    - About: quick_start/index.md
    - Installation: quick_start/installation.md
    - Writing A Program: quick_start/writing_a_program.md
    - Porting From NewSmooth: quick_start/porting_from_newsmooth.md
  - Examples: examples.md
  - API:
    - Main: api/index.md
    - CFrameTrack: api/cframe_track.md
    - Segment: api/segment.md
    - Section: api/section.md
    - TrackGroup: api/track_group.md
    - PhysicsRails: api/physics_rails.md

theme:
  name: material
  palette:
    primary: blue

plugins:
  - search

markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
