site_name: Track Builder
site_description: Documentation for the Track Builder Plugin
site_author: TheEpicTwin
repo_name: Twin1Twin2/track-builder
repo_url: https://github.com/Twin1Twin2/track-builder

nav:
  - Home: index.md
  - Changelog: changelog.md
  - Quick Start:
    - About: quick_start/index.md
    - Installation: quick_start/installation.md
    - Writing A Program: quick_start/writing_a_program.md
    - Porting From NewSmooth: quick_start/porting_from_newsmooth.md
  - Examples: examples.md
  - API:
    - Main: api/index.md
    - CFrameTrack: api/cframe_track.md
    - Segment:
      - Module: api/segment/index.md
      - MeshData: api/segment/mesh_data.md
      - Rail: api/segment/rail.md
      - TrackObject: api/segment/track_object.md
      - MidTrackObject: api/segment/mid_track_object.md
      - Crossbeam: api/segment/crossbeam.md
      - Rect: api/segment/rect.md
      - RectRail: api/segment/rect_rail.md
      - BoxRail: api/segment/box_rail.md
    - BaseSection: api/base_section.md
    - Section: api/section.md
    - TrackGroup: api/track_group.md
    - PhysicsRails: api/physics_rails.md
    - CFrame Util: api/cframe_util.md
    - Vector3 Util: api/vector3_util.md
  - Credits: credits.md

theme:
  name: material
  palette:
    primary: blue

plugins:
  - search

markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
